// const Portfolio = [
//   {
//     symbol: "AAPL",
//     totalQuantity: 20,
//     equityValue: 2500.0,
//     pricePerShare: 125.0,
//   },
//   {
//     symbol: "TSLA",
//     totalQuantity: 5.0,
//     equityValue: 3000.0,
//     pricePerShare: 600.0,
//   },
//   {
//     symbol: "AMZN",
//     totalQuantity: 1.38461538,
//     equityValue: 4500.0,
//     pricePerShare: 150.0,
//   },
//   {

//   "exchangeRate": {
//     "buy": 577,
//     "sell": 560,
//     "base": 560,
//     "currency": "USD"
//   },
//   "fees": {
//     "NGN": {
//       "id": "stocks-ngn",
//       "currency": "NGN",
//       "buy": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 2.34875,
//         "max_fee": 0,
//         "flat": 4.2
//       },
//       "sell": {
//         "limit": 0,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 2.14875,
//         "max_fee": 0,
//         "flat": 4.2
//       }
//     },
//     "USD": {
//       "id": "stocks-usd",
//       "currency": "USD",
//       "symbol": "$",
//       "buy": {
//         "limit": 2500,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 1,
//         "max_fee": 0,
//         "min_fee": 0,
//         "flat": 0
//       },
//       "sell": {
//         "limit": 2500,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 1,
//         "max_fee": 0,
//         "min_fee": 0,
//         "flat": 0
//       }
//     },
//     "CRYPTO": {
//       "id": "crypto-ngn",
//       "currency": "NGN",
//       "buy": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 1,
//         "max_fee": 0,
//         "flat": 0
//       },
//       "buy_limit": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 0.35,
//         "max_fee": 0,
//         "flat": 0
//       },
//       "sell": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 1,
//         "max_fee": 0,
//         "flat": 0
//       },
//       "sell_limit": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 0.35,
//         "max_fee": 0,
//         "flat": 0
//       }
//     },
//     "FIXED_INCOME": {
//       "id": "bonds-ngn",
//       "currency": "NGN",
//       "buy": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 0,
//         "max_fee": 0,
//         "flat": 0
//       },
//       "sell": {
//         "limit": 100000,
//         "processing_percent": 0,
//         "processing_flat": 0,
//         "processing_max": 0,
//         "discount_percent": 0,
//         "discount_flat": 0,
//         "percent": 0,
//         "max_fee": 0,
//         "flat": 0
//       }
//     }
//   }
// }
// ];
export const data = {
    "trending": [
      {
        "_id": "60ff0b45fa3933dbb5611ee0",
        "currency": "USD",
        "symbol": "LCID",
        "__v": 0,
        "ask": "37.93",
        "asset_type": "equity",
        "bid": "37.9",
        "category": "Consumer Cyclical",
        "close": "35.48",
        "high": "39.78",
        "id": "ced916c6-5c45-474b-9649-8a296bd17728",
        "image_url": "https://drivewealth.imgix.net/symbols/lcid_1627272969.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "low": "28.08",
        "market": "NSQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "Lucid Group Inc.",
        "open": "28.54",
        "percent_change": "31.31",
        "prev_close": "27.02",
        "price": "35.48",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635496921457",
        "unique_id": "ced916c6-5c45-474b-9649-8a296bd17728",
        "volume": "378507720",
        "fifty_two_week_high": "39.78",
        "fifty_two_week_low": "16.12"
      },
      {
        "_id": "609a58a174aa24869897ff63",
        "currency": "USD",
        "symbol": "F",
        "__v": 0,
        "ask": "16.87",
        "asset_type": "equity",
        "bid": "16.8",
        "category": "Consumer Cyclical",
        "close": "16.86",
        "fifty_two_week_high": "17.58",
        "fifty_two_week_low": "7.61",
        "high": "17.58",
        "id": "a524e79a-aaac-42c1-acd7-a1a0f8e11cab",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/f.png",
        "inactive": 0,
        "low": "16.71",
        "market": "NYQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "Ford Motor Co.",
        "open": "16.86",
        "percent_change": "8.70",
        "prev_close": "15.51",
        "price": "16.86",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635497188536",
        "unique_id": "a524e79a-aaac-42c1-acd7-a1a0f8e11cab",
        "volume": "215247695",
        "beta": "0.05",
        "volatility_level": "low"
      },
      {
        "_id": "5dd3dcdcda132f47fcd248d8",
        "percent_change": "2.50",
        "prev_close": "148.85",
        "value": "0",
        "market_cap": "2161381967120",
        "volume": "100231940",
        "price": "152.57",
        "open": "149.82",
        "high": "153.165",
        "low": "149.72",
        "ask": "147.45",
        "bid": "147.4",
        "timestamp": "1635497271256",
        "symbol": "AAPL",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Technology",
        "close": "152.57",
        "eps": "0",
        "fifty_two_week_high": "157.26",
        "fifty_two_week_low": "107.32",
        "id": "a67422af-8504-43df-9e63-7361eb0bd99e",
        "image_url": "https://drivewealth.imgix.net/symbols/aapl.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NSQ",
        "name": "Apple, Inc.",
        "pe_ratio": "29.17",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "a67422af-8504-43df-9e63-7361eb0bd99e",
        "dividend": 0.58999998,
        "beta": "0.06",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "60bfa0aa312dbc917406b6b6",
        "currency": "USD",
        "symbol": "SNDL",
        "__v": 0,
        "asset_type": "equity",
        "category": "Healthcare",
        "close": "0.661",
        "high": "0.665",
        "id": "e66e932a-aa04-455c-9401-866fa4e0b450",
        "image_url": "https://drivewealth.imgix.net/symbols/SNDL.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "low": "0.6525",
        "market": "NAQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "Sundial Growers Inc",
        "open": "0.6538",
        "percent_change": "1.30",
        "prev_close": "0.6525",
        "price": "0.661",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635496794813",
        "unique_id": "e66e932a-aa04-455c-9401-866fa4e0b450",
        "volume": "61950253",
        "ask": "0.655",
        "bid": "0.654",
        "fifty_two_week_high": "3.96",
        "fifty_two_week_low": "0.1381"
      },
      {
        "_id": "5fd3b5bc1b32b60fdc1ff59d",
        "id": "5ad46771-6cb1-49c7-b3e4-c7bb1790b751",
        "unique_id": "5ad46771-6cb1-49c7-b3e4-c7bb1790b751",
        "name": "Triterras Inc",
        "image_url": "https://drivewealth.imgix.net/symbols/trit_1607708340.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "symbol": "TRIT",
        "category": "Technology",
        "asset_type": "equity",
        "market": "NMQ",
        "risk_level": "2",
        "currency": "USD",
        "percent_change": "34.49",
        "prev_close": "6.03",
        "high": "9.51",
        "low": "6.8",
        "open": "7.02",
        "market_cap": "518310264",
        "fifty_two_week_high": "15.3",
        "fifty_two_week_low": "4.68",
        "eps": "0",
        "price_to_book": "0",
        "pe_ratio": "0",
        "ask": "7.65",
        "bid": "7.57",
        "value": "0",
        "volume": "61021714",
        "price": "8.11",
        "close": "8.11",
        "timestamp": "1635496916681",
        "inactive": 0,
        "__v": 0,
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "beta": "0.10",
        "volatility_level": "low",
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd2516d",
        "percent_change": "0.21",
        "prev_close": "4.78",
        "value": "0",
        "market_cap": "96848127",
        "volume": "59014765",
        "price": "4.79",
        "open": "4.95",
        "high": "5.12",
        "low": "4.51",
        "ask": "4.64",
        "bid": "4.6",
        "timestamp": "1635497032283",
        "symbol": "PHUN",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Technology",
        "close": "4.79",
        "eps": "0",
        "fifty_two_week_high": "24.04",
        "fifty_two_week_low": "0.6023",
        "id": "ad4f4a35-61d9-42a2-85f9-94ab9ba136c7",
        "image_url": "https://drivewealth.imgix.net/symbols/phun.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NAQ",
        "name": "Phunware Inc",
        "pe_ratio": "0",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "ad4f4a35-61d9-42a2-85f9-94ab9ba136c7",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd24836",
        "percent_change": "-0.92",
        "prev_close": "122.28",
        "value": "0",
        "market_cap": "94637983821",
        "volume": "58008165",
        "price": "121.16",
        "open": "122.855",
        "high": "123.5",
        "low": "120.26",
        "ask": "120.6",
        "bid": "120.42",
        "timestamp": "1635497285925",
        "symbol": "AMD",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Technology",
        "close": "121.16",
        "eps": "0",
        "fifty_two_week_high": "128.08",
        "fifty_two_week_low": "72.5",
        "id": "e9bb06e1-0981-4584-8cf4-18ee9296dcbe",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/amd.png",
        "inactive": 0,
        "market": "NSQ",
        "name": "Advanced Micro Devices, Inc.",
        "pe_ratio": "32.59",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "e9bb06e1-0981-4584-8cf4-18ee9296dcbe",
        "beta": "0.06",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd2491a",
        "percent_change": "1.96",
        "prev_close": "25.06",
        "value": "0",
        "market_cap": "231140454905",
        "volume": "53083146",
        "price": "25.55",
        "open": "25.13",
        "high": "25.635",
        "low": "25.09",
        "ask": "25.6",
        "bid": "25.52",
        "timestamp": "1635497271340",
        "symbol": "T",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Communication Services",
        "close": "25.55",
        "eps": "0",
        "fifty_two_week_high": "33.88",
        "fifty_two_week_low": "25.01",
        "id": "71826b2c-6c4f-4961-bc19-6f219ca5f8b4",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/t.png",
        "inactive": 0,
        "market": "NYQ",
        "name": "AT&T, Inc.",
        "pe_ratio": "-43.36",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "71826b2c-6c4f-4961-bc19-6f219ca5f8b4",
        "dividend": 8.3000004,
        "beta": "0.04",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5e2712dfeeb415623ad5e2dd",
        "id": "ed6f236a-029f-4e07-90c1-986f67d19af8",
        "unique_id": "ed6f236a-029f-4e07-90c1-986f67d19af8",
        "name": "FuelCell Energy Inc",
        "image_url": "https://drivewealth.imgix.net/symbols/fcel.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "symbol": "FCEL",
        "category": "Technology",
        "asset_type": "equity",
        "market": "NMQ",
        "risk_level": "2",
        "currency": "USD",
        "percent_change": "8.14",
        "prev_close": "7",
        "high": "7.94",
        "low": "7.01",
        "open": "7.02",
        "market_cap": "2556862945",
        "fifty_two_week_high": "29.4396",
        "fifty_two_week_low": "1.98",
        "eps": "0",
        "price_to_book": "0",
        "pe_ratio": "-20.16",
        "ask": "7.6",
        "bid": "7.59",
        "value": "0",
        "volume": "52848097",
        "price": "7.57",
        "close": "7.57",
        "timestamp": "1635496947713",
        "inactive": 0,
        "__v": 0,
        "beta": "0.28",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd2488c",
        "percent_change": "9.70",
        "prev_close": "2.68",
        "value": "0",
        "market_cap": "49093568051",
        "volume": "52308015",
        "price": "2.94",
        "open": "2.89",
        "high": "2.96",
        "low": "2.83",
        "ask": "2.93",
        "bid": "2.75",
        "timestamp": "1635497285846",
        "symbol": "ABEV",
        "__v": 0,
        "currency": "USD",
        "asset_type": "adr",
        "category": "Consumer Defensive",
        "close": "2.94",
        "eps": "0",
        "fifty_two_week_high": "3.95",
        "fifty_two_week_low": "2.13",
        "id": "7e14f14b-bad4-4228-b31c-f0b9b105eb48",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/abev.png",
        "inactive": 0,
        "market": "NYQ",
        "name": "Ambev S.A.",
        "pe_ratio": "22.59",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "7e14f14b-bad4-4228-b31c-f0b9b105eb48",
        "dividend": 0.53,
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0,
        "beta": "0",
        "volatility_level": ""
      }
    ],
    "categories": {
      "Technology": {
        "image_url": "https://troveapp.co/img/categories/technology.png",
        "subcategories": [
          "technology",
          "tech",
          "ict",
          "communication services",
          "engineering technology"
        ]
      },
      "Finance": {
        "image_url": "https://troveapp.co/img/categories/finance.png",
        "subcategories": [
          "financial",
          "financial services",
          "other financial institutions",
          "insurance",
          "financial services"
        ]
      },
      "Energy": {
        "image_url": "https://troveapp.co/img/categories/energy.png",
        "subcategories": [
          "energy",
          "petroleum (marketing)",
          "petroleum(marketing)"
        ]
      },
      "Real Estate": {
        "image_url": "https://troveapp.co/img/categories/real-estate.png",
        "subcategories": [
          "real estate",
          "construction/real estate",
          "real estate",
          "hotels and tourism",
          "construction",
          "mortgage companies"
        ]
      },
      "Healthcare": {
        "image_url": "https://troveapp.co/img/categories/healthcare.png",
        "subcategories": [
          "healthcare"
        ]
      },
      "Consumer": {
        "image_url": "https://troveapp.co/img/categories/consumer.png",
        "subcategories": [
          "consumer good",
          "consumer goods",
          "food beverages and tobacco",
          "breweries",
          "consumer defensive",
          "consumer cyclical"
        ]
      },
      "Industrial": {
        "image_url": "https://troveapp.co/img/categories/industrial.png",
        "subcategories": [
          "industrials",
          "industrial goods",
          "chemical and paints",
          "industrial domestic products",
          "automobile and tyre",
          "building materials"
        ]
      },
      "Services": {
        "image_url": "https://troveapp.co/img/categories/services.png",
        "subcategories": [
          "commercial services",
          "airline services",
          "airline service",
          "maritime",
          "services"
        ]
      },
      "ETFs": {
        "image_url": "https://troveapp.co/img/categories/etfs.png",
        "subcategories": [
          
        ]
      },
      "REITS": {
        "image_url": "https://troveapp.co/img/categories/reits.png",
        "subcategories": [
          
        ]
      },
      "Others": {
        "image_url": "https://troveapp.co/img/categories/others.png",
        "subcategories": [
          "road transportation",
          "printing and publishing",
          "computer and office equipment",
          "agriculture",
          "agriculture/agro allied",
          "conglomerates",
          "utilities",
          "basic materials"
        ]
      }
    },
    "top_gainers": [
      {
        "_id": "5fd3b5bc1b32b60fdc1ff59d",
        "id": "5ad46771-6cb1-49c7-b3e4-c7bb1790b751",
        "unique_id": "5ad46771-6cb1-49c7-b3e4-c7bb1790b751",
        "name": "Triterras Inc",
        "image_url": "https://drivewealth.imgix.net/symbols/trit_1607708340.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "symbol": "TRIT",
        "category": "Technology",
        "asset_type": "equity",
        "market": "NMQ",
        "risk_level": "2",
        "currency": "USD",
        "percent_change": "34.49",
        "prev_close": "6.03",
        "high": "9.51",
        "low": "6.8",
        "open": "7.02",
        "market_cap": "518310264",
        "fifty_two_week_high": "15.3",
        "fifty_two_week_low": "4.68",
        "eps": "0",
        "price_to_book": "0",
        "pe_ratio": "0",
        "ask": "7.65",
        "bid": "7.57",
        "value": "0",
        "volume": "61021714",
        "price": "8.11",
        "close": "8.11",
        "timestamp": "1635496916681",
        "inactive": 0,
        "__v": 0,
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "beta": "0.10",
        "volatility_level": "low",
        "sell_only": 0
      },
      {
        "_id": "615b13dbf5ab330a95f658cb",
        "currency": "USD",
        "symbol": "WOLF",
        "__v": 0,
        "ask": "126",
        "asset_type": "equity",
        "bid": "118.5",
        "category": "Technology",
        "close": "121.04",
        "fifty_two_week_high": "129.9",
        "fifty_two_week_low": "60.56",
        "high": "125.37",
        "id": "e5f13076-523e-4912-8aa9-65256af2e4a3",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/cree.png",
        "inactive": 0,
        "low": "105.21",
        "market": "NYQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "Wolfspeed Inc.",
        "open": "107.32",
        "percent_change": "33.20",
        "prev_close": "90.87",
        "price": "121.04",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635497205898",
        "unique_id": "e5f13076-523e-4912-8aa9-65256af2e4a3",
        "volume": "8803197"
      },
      {
        "_id": "5dd3dcddda132f47fcd255b3",
        "percent_change": "33.05",
        "prev_close": "31.62",
        "value": "0",
        "market_cap": "1372861139",
        "volume": "18969991",
        "price": "42.07",
        "open": "42.5",
        "high": "44.66",
        "low": "39.13",
        "ask": "42.9",
        "bid": "42",
        "timestamp": "1635496966536",
        "symbol": "LC",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Financial Services",
        "close": "42.07",
        "eps": "0",
        "fifty_two_week_high": "44.66",
        "fifty_two_week_low": "4.4",
        "id": "8b3116b5-2928-4883-9ddc-b5d85bd262f9",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/lc.png",
        "inactive": 0,
        "market": "NYQ",
        "name": "LendingClub Corporation",
        "pe_ratio": "-5.86",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "8b3116b5-2928-4883-9ddc-b5d85bd262f9",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "60ff0b45fa3933dbb5611ee0",
        "currency": "USD",
        "symbol": "LCID",
        "__v": 0,
        "ask": "37.93",
        "asset_type": "equity",
        "bid": "37.9",
        "category": "Consumer Cyclical",
        "close": "35.48",
        "high": "39.78",
        "id": "ced916c6-5c45-474b-9649-8a296bd17728",
        "image_url": "https://drivewealth.imgix.net/symbols/lcid_1627272969.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "low": "28.08",
        "market": "NSQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "Lucid Group Inc.",
        "open": "28.54",
        "percent_change": "31.31",
        "prev_close": "27.02",
        "price": "35.48",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635496921457",
        "unique_id": "ced916c6-5c45-474b-9649-8a296bd17728",
        "volume": "378507720",
        "fifty_two_week_high": "39.78",
        "fifty_two_week_low": "16.12"
      },
      {
        "_id": "5dd3dcdcda132f47fcd24e23",
        "percent_change": "26.96",
        "prev_close": "55.93",
        "value": "0",
        "market_cap": "1178559881",
        "volume": "927042",
        "price": "71.01",
        "open": "60.81",
        "high": "71.83",
        "low": "59.5",
        "ask": "71.01",
        "bid": "65.57",
        "timestamp": "1635497136433",
        "symbol": "PI",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Technology",
        "close": "71.01",
        "eps": "0",
        "fifty_two_week_high": "79.05",
        "fifty_two_week_low": "24.3601",
        "id": "5f6cc4ed-f0c7-4ae1-ae9a-68475ed352b3",
        "image_url": "https://drivewealth.imgix.net/symbols/pi.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NSQ",
        "name": "Impinj Inc.",
        "pe_ratio": "-19.9",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "5f6cc4ed-f0c7-4ae1-ae9a-68475ed352b3",
        "beta": "0.11",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd25122",
        "percent_change": "20.53",
        "prev_close": "77.16",
        "value": "0",
        "market_cap": "3723932810",
        "volume": "6291747",
        "price": "93",
        "open": "83.19",
        "high": "96.98",
        "low": "82.85",
        "ask": "94.75",
        "bid": "92",
        "timestamp": "1635497042201",
        "symbol": "OSTK",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Consumer Cyclical",
        "close": "93",
        "eps": "0",
        "fifty_two_week_high": "112.2952",
        "fifty_two_week_low": "46.75",
        "id": "149032d1-2bf1-465d-b476-a29eb0e1ccb3",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/ostk.png",
        "inactive": 0,
        "market": "NMQ",
        "name": "Overstock.com, Inc.",
        "pe_ratio": "63.15",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "149032d1-2bf1-465d-b476-a29eb0e1ccb3",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "605a2200252bca04b8af65f5",
        "unique_id": "c99bb558-a22c-413c-87c8-3d1831805bdd",
        "id": "c99bb558-a22c-413c-87c8-3d1831805bdd",
        "symbol": "KOPN",
        "currency": "USD",
        "name": "Kopin Corporation",
        "image_url": "https://drivewealth.imgix.net/symbols/kopn_1616443752.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "asset_type": "equity",
        "percent_change": "19.73",
        "price": "5.4",
        "prev_close": "4.51",
        "close": "5.4",
        "open": "4.51",
        "high": "5.88",
        "low": "4.47",
        "volume": "8876574",
        "fifty_two_week_high": "13.62",
        "fifty_two_week_low": "1.17",
        "price_to_book": "0",
        "market_cap": "672795943",
        "pe_ratio": "-137.5",
        "category": "Technology",
        "market": "NAQ",
        "value": "0",
        "eps": "0",
        "ask": "5.55",
        "bid": "5.5",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "timestamp": "1635496889717",
        "sell_only": 0,
        "inactive": 0,
        "beta": "0.14",
        "risk_level": "2",
        "volatility_level": "low",
        "__v": 0
      },
      {
        "_id": "5dd3dcddda132f47fcd25450",
        "percent_change": "19.21",
        "prev_close": "42.84",
        "value": "0",
        "market_cap": "1954521633",
        "volume": "1351313",
        "price": "51.07",
        "open": "48.03",
        "high": "51.23",
        "low": "47",
        "ask": "51.5",
        "bid": "47.5",
        "timestamp": "1635497008531",
        "symbol": "UCTT",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "technology",
        "close": "51.07",
        "eps": "0",
        "fifty_two_week_high": "65.33",
        "fifty_two_week_low": "21.08",
        "id": "6b59cead-65f7-42e9-80b2-1fe63ecf0cc8",
        "image_url": "https://drivewealth.imgix.net/symbols/uctt.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NSQ",
        "name": "Ultra Clean Holdings Inc",
        "pe_ratio": "25.43",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "6b59cead-65f7-42e9-80b2-1fe63ecf0cc8",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "61520480c0e1a235d62a64f7",
        "currency": "USD",
        "symbol": "GHRS",
        "__v": 0,
        "ask": "22.49",
        "asset_type": "equity",
        "bid": "19.6",
        "category": "Services",
        "close": "20.59",
        "fifty_two_week_high": "26.91",
        "fifty_two_week_low": "12.38",
        "high": "20.99",
        "id": "f6b23874-cfc3-455e-923c-09829acfb6f0",
        "image_url": "https://drivewealth.imgix.net/symbols/GHRS.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "low": "16.3",
        "market": "NMQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "GH RESEARCH PLC",
        "open": "16.93",
        "percent_change": "18.61",
        "prev_close": "17.36",
        "price": "20.59",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635496616147",
        "unique_id": "f6b23874-cfc3-455e-923c-09829acfb6f0",
        "volume": "38292"
      },
      {
        "_id": "5dd3dcdcda132f47fcd24ac7",
        "percent_change": "18.40",
        "prev_close": "10.11",
        "value": "0",
        "market_cap": "1851275011",
        "volume": "5388581",
        "price": "11.97",
        "open": "11.66",
        "high": "12.43",
        "low": "11.02",
        "ask": "12.2",
        "bid": "11.7",
        "timestamp": "1635497217268",
        "symbol": "CYH",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Healthcare",
        "close": "11.97",
        "eps": "0",
        "fifty_two_week_high": "17.04",
        "fifty_two_week_low": "4.39",
        "id": "e957764f-3a44-498f-a6ce-1d8fbdc2ee19",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/cyh.png",
        "inactive": 0,
        "market": "NYQ",
        "name": "Community Health Systems, Inc.",
        "pe_ratio": "3.9",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "e957764f-3a44-498f-a6ce-1d8fbdc2ee19",
        "beta": "0.16",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      }
    ],
    "top_losers": [
      {
        "_id": "60d249c3e7c99a3b27885f6c",
        "currency": "USD",
        "symbol": "RFL",
        "__v": 0,
        "ask": "7.4",
        "asset_type": "equity",
        "bid": "7.04",
        "category": "",
        "close": "8.09",
        "fifty_two_week_high": "66.44",
        "fifty_two_week_low": "5.9",
        "high": "9",
        "id": "fbc81518-f05e-458b-b739-f00d34de6b3d",
        "image_url": "https://drivewealth.imgix.net/symbols/RFL.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "low": "5.9",
        "market": "NYQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "RAFAEL HOLDINGS INC-CLASS B",
        "open": "6.61",
        "percent_change": "-73.19",
        "prev_close": "30.17",
        "price": "8.09",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635496717600",
        "unique_id": "fbc81518-f05e-458b-b739-f00d34de6b3d",
        "volume": "24507984",
        "beta": "0.13",
        "volatility_level": "low"
      },
      {
        "_id": "6001a12db387e204a319a363",
        "id": "ec60a4ae-a404-4d6a-8e53-0cccc198e3ce",
        "unique_id": "ec60a4ae-a404-4d6a-8e53-0cccc198e3ce",
        "name": "Brightcove Inc",
        "image_url": "https://drivewealth.imgix.net/symbols/bcov_1610659991.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "symbol": "BCOV",
        "category": "Technology",
        "asset_type": "equity",
        "market": "NSQ",
        "risk_level": "2",
        "currency": "USD",
        "percent_change": "-20.74",
        "prev_close": "11.86",
        "high": "9.77",
        "low": "9.2",
        "open": "9.2",
        "market_cap": "566901919",
        "fifty_two_week_high": "25.26",
        "fifty_two_week_low": "9.2101",
        "eps": "0",
        "price_to_book": "0",
        "pe_ratio": "79.07",
        "ask": "9.4",
        "bid": "9.2",
        "value": "0",
        "volume": "2451582",
        "price": "9.4",
        "close": "9.4",
        "timestamp": "1635496907198",
        "inactive": 0,
        "__v": 0,
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "beta": "0.20",
        "volatility_level": "low",
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd251ef",
        "percent_change": "-20.46",
        "prev_close": "73.72",
        "value": "0",
        "market_cap": "2803863680",
        "volume": "2329586",
        "price": "58.64",
        "open": "66.09",
        "high": "66.34",
        "low": "57.54",
        "ask": "59.43",
        "bid": "58.64",
        "timestamp": "1635497028523",
        "symbol": "PRLB",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Capital Goods",
        "close": "58.64",
        "eps": "0",
        "fifty_two_week_high": "286.57",
        "fifty_two_week_low": "57.54",
        "id": "ead548d5-709a-4e51-8d41-54928dbec9a3",
        "image_url": "https://drivewealth.imgix.net/symbols/prlb.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NYQ",
        "name": "Proto Labs, Inc.",
        "pe_ratio": "53.58",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "ead548d5-709a-4e51-8d41-54928dbec9a3",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcddda132f47fcd25444",
        "percent_change": "-17.57",
        "prev_close": "345.66",
        "value": "0",
        "market_cap": "48936576904",
        "volume": "21577765",
        "price": "284.93",
        "open": "286.26",
        "high": "303.9799",
        "low": "278",
        "ask": "287.7",
        "bid": "281",
        "timestamp": "1635497008557",
        "symbol": "TWLO",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Technology",
        "close": "284.93",
        "eps": "0",
        "fifty_two_week_high": "457.3",
        "fifty_two_week_low": "254.82",
        "id": "69038234-efbd-4b8e-9ad9-b73a7bac01fa",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/twlo.png",
        "inactive": 0,
        "market": "NYQ",
        "name": "Twilio",
        "pe_ratio": "-90.78",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "69038234-efbd-4b8e-9ad9-b73a7bac01fa",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcddda132f47fcd2547d",
        "percent_change": "-17.06",
        "prev_close": "8.85",
        "value": "0",
        "market_cap": "2030768282",
        "volume": "25191758",
        "price": "7.34",
        "open": "7.11",
        "high": "7.54",
        "low": "7.07",
        "ask": "7.27",
        "bid": "7.26",
        "timestamp": "1635497003147",
        "symbol": "TIGR",
        "__v": 0,
        "currency": "USD",
        "asset_type": "adr",
        "category": "Financial",
        "close": "7.34",
        "eps": "0",
        "fifty_two_week_high": "38.5",
        "fifty_two_week_low": "4.3",
        "id": "8f247616-bd17-43e0-a58b-a1a895d0000b",
        "image_url": "https://drivewealth.imgix.net/symbols/tigr.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NSQ",
        "name": "UP Fintech Holding Limited",
        "pe_ratio": "0",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "8f247616-bd17-43e0-a58b-a1a895d0000b",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0,
        "beta": "0",
        "volatility_level": ""
      },
      {
        "_id": "616458d93dcc1e2d204314e6",
        "currency": "USD",
        "symbol": "LND",
        "__v": 0,
        "ask": "7.08",
        "asset_type": "adr",
        "bid": "2.2",
        "category": "",
        "close": "5.11",
        "fifty_two_week_high": "6.83",
        "fifty_two_week_low": "3.76",
        "high": "5.38",
        "id": "f65b7f0a-a55a-43a5-9822-91d0276d54ef",
        "image_url": "https://drivewealth.imgix.net/symbols/LND.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "low": "4.85",
        "market": "NYQ",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "name": "BRASILAGRO-CIA BRA - SPN ADR",
        "open": "5.38",
        "percent_change": "-16.91",
        "prev_close": "6.15",
        "price": "5.11",
        "risk_level": "2",
        "sell_only": 0,
        "timestamp": "1635496557903",
        "unique_id": "f65b7f0a-a55a-43a5-9822-91d0276d54ef",
        "volume": "93318",
        "dividend": 9.53
      },
      {
        "_id": "5dd3dcddda132f47fcd25585",
        "percent_change": "-15.77",
        "prev_close": "2.22",
        "value": "0",
        "market_cap": "112989432",
        "volume": "520662",
        "price": "1.87",
        "open": "2.09",
        "high": "2.1",
        "low": "1.77",
        "ask": "1.99",
        "bid": "1.85",
        "timestamp": "1635496973758",
        "symbol": "ZVO",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "services",
        "close": "1.87",
        "eps": "0",
        "fifty_two_week_high": "7.3399",
        "fifty_two_week_low": "1.77",
        "id": "6a819f1d-0273-4ba6-85b0-3d619fe07509",
        "image_url": "https://drivewealth.imgix.net/symbols/zvo.png?fit=fillmax&w=125&h=125&bg=FFFFFF",
        "inactive": 0,
        "market": "NSQ",
        "name": "Zovio Inc",
        "pe_ratio": "0",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "6a819f1d-0273-4ba6-85b0-3d619fe07509",
        "beta": "0.26",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd24879",
        "percent_change": "-15.18",
        "prev_close": "191.16",
        "value": "0",
        "market_cap": "15527699784",
        "volume": "2766399",
        "price": "162.14",
        "open": "169.07",
        "high": "172.46",
        "low": "156.01",
        "ask": "178",
        "bid": "127",
        "timestamp": "1635497285862",
        "symbol": "ALNY",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Healthcare",
        "close": "162.14",
        "eps": "0",
        "fifty_two_week_high": "212",
        "fifty_two_week_low": "119.29",
        "id": "a0f44eab-fc53-4b36-a9ae-ca39eec8083c",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/alny.png",
        "inactive": 0,
        "market": "NSQ",
        "name": "Alnylam Pharmaceuticals, Inc.",
        "pe_ratio": "-17.5",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "a0f44eab-fc53-4b36-a9ae-ca39eec8083c",
        "beta": "0.12",
        "volatility_level": "low",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd24b77",
        "percent_change": "-15.05",
        "prev_close": "10.1",
        "value": "0",
        "market_cap": "1167985147",
        "volume": "3760239",
        "price": "8.58",
        "open": "9.19",
        "high": "9.27",
        "low": "8.42",
        "ask": "8.6",
        "bid": "8.26",
        "timestamp": "1635497202939",
        "symbol": "DBD",
        "__v": 0,
        "currency": "USD",
        "asset_type": "equity",
        "category": "Technology",
        "close": "8.58",
        "eps": "0",
        "fifty_two_week_high": "17.3",
        "fifty_two_week_low": "5.97",
        "id": "d0fb039e-2595-4123-9524-73fb7a9c0575",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/dbd.png",
        "inactive": 0,
        "market": "NYQ",
        "name": "Diebold, Incorporated",
        "pe_ratio": "-4.31",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "d0fb039e-2595-4123-9524-73fb7a9c0575",
        "beta": "0",
        "volatility_level": "",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0
      },
      {
        "_id": "5dd3dcdcda132f47fcd24b56",
        "percent_change": "-15.00",
        "prev_close": "3.6",
        "value": "0",
        "market_cap": "660338978",
        "volume": "1510272",
        "price": "3.06",
        "open": "3.26",
        "high": "3.2618",
        "low": "2.96",
        "ask": "3.63",
        "bid": "3.62",
        "timestamp": "1635497202923",
        "symbol": "DBVT",
        "__v": 0,
        "currency": "USD",
        "asset_type": "adr",
        "category": "Healthcare",
        "close": "3.06",
        "eps": "0",
        "fifty_two_week_high": "7.38",
        "fifty_two_week_low": "1.35",
        "id": "859bfc3c-7609-47b8-b03d-3b6a3bb3d3cd",
        "image_url": "https://d3an3cesqmrf1x.cloudfront.net/images/symbols/dbvt.png",
        "inactive": 0,
        "market": "NSQ",
        "name": "DBV Technologies S.A.",
        "pe_ratio": "0",
        "price_to_book": "0",
        "risk_level": "2",
        "unique_id": "859bfc3c-7609-47b8-b03d-3b6a3bb3d3cd",
        "market_status": {
          "value": "closed",
          "label": "Closed",
          "preMarket": true
        },
        "sell_only": 0,
        "beta": "0",
        "volatility_level": ""
      }
    ],
    "market_news": [
      {
        "news_url": "https://www.fool.com/investing/2021/10/29/this-1-strategy-could-save-you-during-a-stock-mark/",
        "image_url": "https://cdn.snapi.dev/images/v1/e/4/urlhttps3a2f2fgfoolcdncom2feditorial2fimages2f6488182fworried-man-gettyimages-483188935jpgw700opresize-1075797.jpg",
        "title": "This 1 Strategy Could Save You During a Stock Market Crash",
        "text": "Worried about a downturn? Here's a key move to make.",
        "source_name": "The Motley Fool",
        "date": 1635504540000,
        "topics": [
          
        ],
        "sentiment": "Negative",
        "type": "Article"
      },
      {
        "news_url": "https://www.proactiveinvestors.com//companies/news/964687/us-stocks-set-to-end-the-week-on-the-back-foot-after-quarterly-earnings-disappoinment-from-both-apple-and-amazon-964687.html?SNAPI",
        "image_url": "https://cdn.snapi.dev/images/v1/a/0/1635503945-shutterstock-391056130-1075782.jpg",
        "title": "US stocks set to end the week on the back foot after quarterly earnings disappoinment from both Apple and Amazon",
        "text": "US stocks look set to end the week on the back foot after quarterly reports released after-hours on Thursday from both Apple Inc and Amazon Inc showed the impact of supply-chain problems and tight labor markets. Futures for the Dow Jones Industrial Average were 0.2% lower in Friday, while those for the S&P 500 fell 0.5%, and contracts for the tech-laden Nasdaq-100 shed 0.9% weighed by disappointments from two of its biggest components.",
        "source_name": "Proactive Investors",
        "date": 1635503984000,
        "topics": [
          "earnings"
        ],
        "sentiment": "Negative",
        "type": "Article"
      },
      {
        "news_url": "https://seekingalpha.com/article/4463371-frothy-overvalued-market-dont-stop-believing",
        "image_url": "https://cdn.snapi.dev/images/v1/g/r/wedw322-6wdaea84k2-1075760.jpg",
        "title": "More Gas In The Tank, More Bumps On The Ride",
        "text": "I've never seen a market that felt so frothy (and in some pockets “overvalued”) that simultaneously had so many high quality stocks that were still “on sale”. While everyone thinks yields will keep rising once they start tapering, history shows that yields may stop rising upon announcement.",
        "source_name": "Seeking Alpha",
        "date": 1635502677000,
        "topics": [
          "paylimitwall"
        ],
        "sentiment": "Negative",
        "type": "Article"
      },
      {
        "news_url": "https://www.reuters.com/article/usa-fed-inflation-powell/the-feds-inflation-story-in-charts-idUSKBN2HJ18Y",
        "image_url": "https://cdn.snapi.dev/images/v1/v/5/m02d20211029t2i1579531462w940fhfwllplsqrlynxmpeh9s0kg-1075757.jpg",
        "title": "The Fed's inflation story, in charts",
        "text": "Federal Reserve Chair Jerome Powell, in a high-profile speech in August, outlined the arguments for why the current bout of high U.S. inflation will be \"transitory,\" and moderate on its own over time.",
        "source_name": "Reuters",
        "date": 1635502200000,
        "topics": [
          
        ],
        "sentiment": "Neutral",
        "type": "Article"
      },
      {
        "news_url": "https://markets.businessinsider.com/news/stocks/stock-market-today-apple-amazon-earnings-ether-record-high-2021-10",
        "image_url": "https://cdn.snapi.dev/images/v1/6/0/60fa6ce3fc253600181ffc3cformatjpeg-1075721.jpg",
        "title": "US stock futures tip lower after Apple and Amazon earnings miss estimates, while ether hits a record high",
        "text": "Both mega-cap tech companies cited supply-chain troubles as the issue, raising fears about related impact in the next quarter.",
        "source_name": "Business Insider",
        "date": 1635500488000,
        "topics": [
          "earnings",
          "paylimitwall"
        ],
        "sentiment": "Negative",
        "type": "Article"
      },
      {
        "news_url": "https://seekingalpha.com/article/4463372-rates-spark-inflation-inflation-inflation",
        "image_url": "https://cdn.snapi.dev/images/v1/j/9/day-hagan-tech-talk-volatility-of-a-different-type-440x250-1067601-1069806-1075720.jpg",
        "title": "Rates Spark: Inflation, Inflation, Inflation",
        "text": "The European Central Bank was merely the prelude to next week's Fed and Bank of England meetings, where policy tightening is expected to be announced. Against this backdrop, and with high inflation to remain in the headlines, the ECB's feeble attempt to push back against market pricing proved futile.",
        "source_name": "Seeking Alpha",
        "date": 1635500400000,
        "topics": [
          "paylimitwall"
        ],
        "sentiment": "Negative",
        "type": "Article"
      },
      {
        "news_url": "https://www.barrons.com/articles/stock-market-today-51635499631",
        "image_url": "https://cdn.snapi.dev/images/v1/1/6/1635417238-the-new-york-stock-exchange-is-an-american-stock-exchange-located-at-11-wall-street-1072675-1075772.jpg",
        "title": "Nasdaq and S&P 500 Set to Slip From Records, Energy Earnings Ahead—and What Else Is Happening in the Stock Market Today",
        "text": "The stock market was set to slip back from record highs Friday as investor sentiment took a hit from Apple and Amazon earnings, which showed how the technology giants have been pinched by global supply-chain disruptions.",
        "source_name": "Barrons",
        "date": 1635499680000,
        "topics": [
          "paywall"
        ],
        "sentiment": "Negative",
        "type": "Article"
      },
      {
        "news_url": "https://www.reuters.com/business/yellen-expects-inflationary-pressures-ease-by-second-half-2022-2021-10-29/",
        "image_url": "https://cdn.snapi.dev/images/v1/m/0/m02d20211029t2i1579525575w940fhfwllplsqrlynxmpeh9s0i2-1075722.jpg",
        "title": "Yellen expects inflationary pressures to ease by second half of 2022",
        "text": "U.S. Treasury Secretary Janet Yellen on Friday said she still sees inflation as a temporary result of severe supply chain bottlenecks, and expects price increases to normalize during 2022 as people get back to work and demand shifts back to services.",
        "source_name": "Reuters",
        "date": 1635499440000,
        "topics": [
          "Political"
        ],
        "sentiment": "Neutral",
        "type": "Article"
      },
      {
        "news_url": "https://www.cnbc.com/2021/10/29/treasury-secretary-yellen-says-spending-bills-will-be-anti-inflationary-lowering-important-costs.html",
        "image_url": "https://cdn.snapi.dev/images/v1/1/0/106948656-16328410702021-09-28t145558z-1171690429-rc22zp9t2yxh-rtrmadp-0-health-coronavirus-powell-yellen-1075712.jpeg",
        "title": "Treasury Secretary Yellen says spending bills will be anti-inflationary, lowering important costs",
        "text": "Treasury Secretary Janet Yellen asserted Friday that the administration's infrastructure spending proposal will lower inflation by reducing several costs vital to households.",
        "source_name": "CNBC",
        "date": 1635499004000,
        "topics": [
          "Political"
        ],
        "sentiment": "Neutral",
        "type": "Article"
      },
      {
        "news_url": "https://seekingalpha.com/article/4463360-real-gdp-in-third-quarter-disappointing-to-many",
        "image_url": "https://cdn.snapi.dev/images/v1/k/y/sikdjd2-1075710.jpg",
        "title": "Real GDP In The Third Quarter: Disappointing To Many",
        "text": "Real GDP was 4.9 percent higher in the third quarter of 2021 than it was in the third quarter of 2020. Many analysts are disappointed with this result. Where we go from here is still a big question, as many analysts see economic growth dropping off as we go into 2022 and 2023.",
        "source_name": "Seeking Alpha",
        "date": 1635498449000,
        "topics": [
          "paylimitwall"
        ],
        "sentiment": "Negative",
        "type": "Article"
      }
    ]
 }
  console.log(data.trending)
